name: Matrix Multiplication with Singularity Container

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      
    - uses: Bacondish2023/setup-googletest@v1
      with:
        tag: v1.14.0

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run Tests
      run: ./build/test_multiplication

    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3

    - name: Create Singularity container
      run: singularity build --fakeroot Singularity.sif SingularityCompile.def

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: singularity-container
        path: Singularity.sif

    - name: Run Singularity container
      run: mpirun -n 2 singularity run Singularity.sif /opt/main
