name: Matrix Multiplication with Singularity Container

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3

    - name: Create a Singularity container
      run: singularity build --fakeroot Singularity.sif Singularity.def

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: singularity-container
        path: Singularity.sif

    - name: Run a singularity container
      run: singularity run Singularity.sif /opt/main
