name: Matrix Multiplication

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      
    - uses: Bacondish2023/setup-googletest@v1
      with:
        tag: v1.14.0

    # - name: Setup googletest
    #   run: cd ${{github.workspace}}/googletest && sudo cmake CMakeLists.txt && cd ..

    # - name: Install gtest manually
    #   run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run Tests
      run: ./build/test_multiplication
