name: Matrix Multiplication with Singularity Container

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
    
    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3

    # - name: Configure CMake
    #   run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    # - name: Build
    #   run: cmake --build ${{github.workspace}}/build

    - name: Create Singularity container
      run: singularity build --fakeroot Singularity.sif Singularity.def

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: singularity-container
        path: Singularity.sif

    # - name: Run Singularity container
    #   run: singularity run Singularity.sif

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Tranfer with scp
      run: sshpass -p ${{ secrets.PASSWORDTZ }} scp -o StrictHostKeyChecking=no Singularity.sif job.sh ${{ secrets.USERTZ }}@login.g100.cineca.it:/g100/home/usertrain/${{ secrets.USERTZ }}

    - name: Run job
      run: sshpass -p ${{ secrets.PASSWORDTZ }} ssh -o StrictHostKeyChecking=no ${{ secrets.USERTZ }}@login.g100.cineca.it:/g100/home/usertrain/${{ secrets.USERTZ }} "sbatch job.sh"
    # ssh-keygen -f "/home/runner/.ssh/known_hosts" -R "login.g100.cineca.it"

