name: Matrix Multiplication

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      
    - uses: Bacondish2023/setup-googletest@v1
      with:
        tag: v1.14.0

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run Tests
      run: ./build/test_multiplication

    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3

    - name: Create a Singularity container
      run: singularity build Singularity.sif Singularity.def

#    - name: Run a singularity container
#      run: singularity run Singularity.sif
