name: Matrix Multiplication

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1

<<<<<<< HEAD
    - name: Setup googletest
      run: cd googletest && sudo cmake CMakelists.txt && cd ..
=======
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
>>>>>>> 966e94fd484cbe6353cb70c2a5f03e107723ec22

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

<<<<<<< HEAD
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
=======
   - name: Build
     run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
>>>>>>> 966e94fd484cbe6353cb70c2a5f03e107723ec22

    - name: Run Tests
      run: ./build/test_multiplication
